### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by frozencemetery** [agix/NetBinaryFormatterParser#1]
Hi, thanks for writing this tool!  It is however missing a license, which means that until one is added, it's not technically open source.  If you're not sure what license to choose, [this website](https://choosealicense.com/) may help with that.

**Comment by jnsnow** [comment]
I feel bad now because I had just written an email to the author to ask for a license. We accidentally ganged up on them!

**Comment by agix** [comment]
Hello guys, thank you for your interest.

I just added the MIT License. Enjoy !
